#! /usr/bin/env lua
-- Lua configuration for automatically inserting the commit message generated by the script

-- Function to yank the current or last selection to a variable
function EyamlEncrypt()
	vim.cmd('normal! gv"xy')
	TXT = vim.fn.getreg("x")
	local num_sel_lines = vim.fn.getpos("'>")[2] - vim.fn.getpos("'<")[2] + 1
	if num_sel_lines > 5 then
		SHELLCMD = "eyaml encrypt -o block --stdin 2> /dev/null"
		APPEND = ">\n"
	else
		SHELLCMD = "eyaml encrypt -o string --stdin 2> /dev/null"
		APPEND = ""
	end
	local i = string.find(TXT, "ENC[")
	if i ~= nil then
		SHELLCMD = "eyaml decrypt --stdin 2> /dev/null"
		APPEND = ""
	end
	local output = vim.fn.system(SHELLCMD, TXT)
	vim.fn.setreg("x", APPEND .. string.gsub(output, "[\r\n]*$", ""))
	vim.g.test = vim.fn.getreg("x")
	vim.cmd('normal! gv"xp')
end

-- Function to create git commit message
function GenCommitMsg()
	local output = vim.fn.system("git_commit_msg.py")
	vim.fn.setreg("a", output)
	vim.cmd("normal! gg0")
	vim.cmd('normal! "aP')
	vim.cmd("normal! :2")
end
